### ISSUE TITLE
Node-sass veranderen naar dart-sass

### ISSUE THREAD

**Issue by AxelVerstappen** [OnroerendErfgoed/aurelia-pikaday-datepicker#28]
Momenteel zijn er issues met nieuwere python versies waardoor de build / install van deze repo faalt.
Temp workaround pyenv: 

Installeer eerst de build dependencies
https://github.com/pyenv/pyenv/wiki#suggested-build-environment

Installeer pyenv
https://github.com/pyenv/pyenv

Installeer met pyenv python 2.7.18 & switch naar python 2.7.18
https://www.python.org/downloads/release/python-2718/

**Comment by roefem** [comment]
Aurelia datepicker is verhuisd naar oerelia, deze package zal worden gearchiveerd
